name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Clean old build
        run: rm -rf Build

      - name: Build
        run: |
          xcodebuild \
            -configuration debug \
            -scheme "Portfolio" \
            -sdk macosx \
            -destination 'platform=macOS' \
            -derivedDataPath ".build/derivedData"
          .build/derivedData/Build/Products/debug/Portfolio

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
